name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  solution-file-full-path: 
    description: 'Full Path to the solution file'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.solution-file-full-path }}