name: 'Nuget Prerelease package detection'
description: 'Stops People merging Pre-Release Nuget References'
inputs:
  solution-file-full-path: 
    description: 'Full Path to the solution file'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.solution-file-full-path }}